# Generated by Django 4.1.11 on 2023-10-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(default='-', max_length=100)),
                ('nickname', models.CharField(default='-', max_length=150)),
                ('telephone', models.CharField(default='-', max_length=100)),
                ('address', models.CharField(default='-', max_length=100)),
                ('gender', models.CharField(default='-', max_length=20)),
                ('date_birth', models.CharField(default='-', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.CharField(default=None, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AutoIncrementCounter',
            fields=[
                ('_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('counter', models.IntegerField(default=1)),
            ],
        ),
    ]
