# Generated by Django 4.1.11 on 2023-10-02 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appSignUp', '0002_alter_customuser_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_active',
        ),
    ]
