# Generated by Django 4.1.11 on 2023-10-03 07:49

import admManageQuestions.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArrayFiller',
            fields=[
                ('pertanyaan', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('jawaban', models.CharField(max_length=200)),
                ('deskripsi', models.CharField(max_length=200)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionListTemplate',
            fields=[
                ('question_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', djongo.models.fields.ArrayField(default=[], model_container=admManageQuestions.models.ArrayFiller)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionListUser',
            fields=[
                ('user_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('question_set', djongo.models.fields.ArrayField(default=[], model_container=admManageQuestions.models.QuestionListTemplate)),
            ],
        ),
    ]
